# Generated by Django 3.0.8 on 2021-08-10 19:24

import os

from django.conf import settings
from django.db import migrations


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model("sites", "Site")
    domain = os.getenv("DEFAULT_SITE_DOMAIN", "example.com")

    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID, defaults={"domain": domain, "name": domain}
    )


class Migration(migrations.Migration):

    dependencies = [("sites", "0002_alter_domain_unique")]

    operations = [migrations.RunPython(update_site_name)]
