# Generated by Django 3.0.8 on 2021-08-08 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210808_0150'),
        ('menus', '0004_auto_20210808_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time when object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of last object modification.', verbose_name='modified at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicator to know if a object was deleted or not', verbose_name='soft deleted status')),
                ('instructions', models.TextField(blank=True, help_text='Specify customizations (e.g. no tomatoes in the salad)', verbose_name='instruccions')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='users.Employee', verbose_name='employee')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='menus.Meal', verbose_name='meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to='menus.Menu', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
