# Generated by Django 3.0.8 on 2021-08-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210809_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, help_text='Specify customizations (e.g. no tomatoes in the salad)', verbose_name='instructions'),
        ),
    ]
