# Generated by Django 3.0.8 on 2021-08-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time when object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of last object modification.', verbose_name='modified at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicator to know if a object was deleted or not', verbose_name='soft deleted status')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
    ]
