# Generated by Django 3.0.8 on 2021-08-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time when object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of last object modification.', verbose_name='modified at')),
                ('option', models.PositiveSmallIntegerField(default=32767, help_text='Option number in menu (useful for ordering).', verbose_name='option')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_options', related_query_name='menu_option', to='menus.Meal', verbose_name='meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_options', related_query_name='menu_option', to='menus.Menu', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'menu option',
                'verbose_name_plural': 'menu options',
                'db_table': 'menus_menu_option',
                'ordering': ['option', '-created'],
            },
        ),
    ]
