# Generated by Django 3.0.8 on 2021-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20210808_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(error_messages={'unique': 'A menu with that date already exists.'}, unique=True, verbose_name='date'),
        ),
        migrations.AddConstraint(
            model_name='menuoption',
            constraint=models.UniqueConstraint(fields=('menu', 'meal'), name='menu_option_menu_meal_unique'),
        ),
    ]
