# Generated by Django 3.0.8 on 2021-08-09 01:16

import backend_test.menus.models.menus
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20210808_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, help_text='Indicator to know if a object was deleted or not', verbose_name='soft deleted status'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(error_messages={'unique': 'A menu with that date already exists.'}, unique=True, validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.localdate)], verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, help_text='Indicator to know if a object was deleted or not', verbose_name='soft deleted status'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=backend_test.menus.models.menus.generate_unique_uuid, editable=False, unique=True),
        ),
    ]
