# Generated by Django 3.0.8 on 2021-08-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20210809_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'permissions': [('send_slack_reminder', 'Send slack reminder')], 'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
    ]
