# Generated by Django 3.0.8 on 2021-08-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time when object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of last object modification.', verbose_name='modified at')),
                ('name', models.CharField(max_length=85, verbose_name='name')),
                ('type', models.CharField(choices=[('country', 'Country'), ('administrative_area_level_1', 'Administrative area level 1'), ('administrative_area_level_2', 'Administrative area level 2'), ('locality', 'Locality'), ('neighborhood', 'Neighborhood')], max_length=27, verbose_name='type')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations_location', related_query_name='location_location', to='locations.Location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('location', 'type', 'name'), name='location_location_type_name_unique'),
        ),
    ]
