# Generated by Django 3.0.8 on 2021-08-07 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210807_2144'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time when object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time of last object modification.', verbose_name='modified at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicator to know if a object was deleted or not', verbose_name='soft deleted status')),
                ('slack_username', models.CharField(error_messages={'unique': 'A user with that slack username already exists.'}, max_length=50, unique=True, verbose_name='slack username')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='employee', to='locations.Location', verbose_name='location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
