# Generated by Django 3.0.8 on 2021-08-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210807_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
